FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Chicago
RUN chmod 1777 /tmp

COPY requirements.txt ./
RUN apt-get update && apt-get install -y --no-install-recommends gcc make python3-dev python3-pip && \
    python3 -m pip install -r requirements.txt && \
    apt-get remove -y gcc make python3-dev && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/* 

COPY app /app
WORKDIR /app
CMD [ "python3", "-u", "./app.py" ]